work_group: ${TEAM:amd}
user_name: ${USER:root}
exp_name: ${EXP_NAME:exp_instella_moe_gated_farskip_overlap_pretraining}
workspace: ./output

platform:
  config: platform_azure.yaml
  overrides:
    master_sink_level: INFO

modules:
  pre_trainer:
    framework: megatron
    config: pre_trainer.yaml

    # model to run
    model: ${PRIMUS_MODEL:instella_16B_gated_farskip_overlap}.yaml
    overrides:
      # log
      wandb_project: "Primus_Instella_MoE_Farskip_Overlap_Pretrain"
      disable_wandb: true # turn on for wandb logging
      stderr_sink_level: DEBUG
      manual_gc: true
      manual_gc_interval: 100

      moe_router_force_load_balancing: false # debugging only
      moe_router_dtype: fp32
      log_avg_skip_iterations: 2
      log_avg_reset_interval: 5

      train_iters: 443876
      eval_iters: 0
      micro_batch_size: 8
      global_batch_size: 4096
      seq_length: ${PRIMUS_SEQ_LENGTH:4096}
      max_position_embeddings: ${PRIMUS_MAX_POSITION_EMBEDDINGS:4096}
      lr: 4.0e-4
      min_lr: 4.0e-5
      lr_warmup_iters: 2000
      lr_decay_style: WSD
      lr_wsd_decay_style: cosine
      lr_wsd_decay_iters: 100000
      weight_decay: 0.1
      adam_beta1: 0.9
      adam_beta2: 0.95
      eod_mask_loss: true
      init_method_std: 0.02
      norm_epsilon: 1.0e-6

      # parallel
      tensor_model_parallel_size: ${PRIMUS_TP:1}
      pipeline_model_parallel_size: ${PRIMUS_PP:1}
      expert_model_parallel_size: ${PRIMUS_EP:8}
      overlap_grad_reduce: true
      overlap_param_gather: true

      # fusion
      moe_permute_fusion: false
      gradient_accumulation_fusion: false
      moe_use_legacy_grouped_gemm: false
      moe_use_fused_router_with_aux_score: false
      fused_padded_mla_attention: false

      # ckpt
      finetune: false
      auto_continue_train: true
      load: null
      no_load_optim: null
      no_load_rng: null
      save: /outputs/path/to/checkpoints/pretrain_instella_16B_gated_farskip_overlap
      save_interval: 1000
      no_save_optim: null
      no_save_rng: null
      disable_last_saving: false
      ckpt_format: torch
      # Turbo
      enable_primus_turbo: true
      use_turbo_attention: true
      use_turbo_grouped_mlp: true

      # pretrain mixture. Each path is a tokenized shard
      # prefix (.bin/.idx) update to real data mixture paths
      # real sources will span multiple shards, two sample shards are shown for first source to demonstrate
      data_cache_path: /data/path/to/pretrain/cache
      num_dataset_builder_threads: 8
      train_data_path:
      # nemotron_cc_v2 (Diverse-QA, High-Quality, High-Quality-Synthetic, Medium-High-Quality, Medium-Quality)
      - /data/path/to/pretrain/nemotron_cc_v2/shard_0000
      - /data/path/to/pretrain/nemotron_cc_v2/shard_0001
      # ...
      # refinecode (python, java, cpp, csharp, go, php, javascript, html, c, text, code_others, data)
      - /data/path/to/pretrain/refinecode/shard_0000
      # nemotron_code
      - /data/path/to/pretrain/nemotron_code/shard_0000
      # nemotron_sft (Nemotron-SFT-Code, Nemotron-SFT-General, Nemotron-SFT-MATH)
      - /data/path/to/pretrain/nemotron_sft/shard_0000
      # megamath (megamath-web, megamath-web-pro, megamath-code, megamath-qa, megamath-text-code-block, megamath-translated-code)
      - /data/path/to/pretrain/megamath/shard_0000
      # nemotron_cc_math (3, 4plus, 4plus_MIND)
      - /data/path/to/pretrain/nemotron_cc_math/shard_0000
      # finemath (finemath-3plus, finemath-4plus, infiwebmath-3plus, infiwebmath-4plus)
      - /data/path/to/pretrain/finemath/shard_0000
      # txt360
      - /data/path/to/pretrain/txt360/shard_0000

      valid_data_path: null
      test_data_path: null
