bases:
  - deepseek_v3_base.yaml

# https://huggingface.co/deepseek-ai/DeepSeek-V3
# 671B total params, 37B active params

tokenizer_type: DeepSeekV3Tokenizer
tokenizer_model: deepseek-ai/DeepSeek-V3

# farskip
use_simple_farskip_layer: false # turns on farskip (reference mode)
use_overlapped_farskip_layer: true # turns on farskip
farskip_overlap_associative_add: true
attn_only_farskip: false
mlp_only_farskip: false
moe_shared_expert_overlap: false # required for the simple implementation version

# model
num_layers: 27
hidden_size: 2048
ffn_hidden_size: 10944
num_attention_heads: 16
# mla
q_lora_rank: null
kv_lora_rank: 512
qk_head_dim: 96
qk_pos_emb_head_dim: 32
v_head_dim: 128
kv_channels: 128
gated_attention: true
# mtp
mtp_num_layers: 1
moe_aux_loss_coeff: 0.0001 # aux_loss_alpha
mtp_loss_scaling_factor: 0.3
# moe
moe_layer_freq: "([0]*1+[1]*26)"
num_experts: 64
# num_shared_experts: 2
moe_ffn_hidden_size: 1408
moe_shared_expert_intermediate_size: 2816 # num_shared_experts * moe_ffn_hidden_size

# no group in deepseek v2 lite
expert_model_parallel_size: 8
moe_router_num_groups: null # int
moe_router_group_topk: null # int
moe_router_topk_scaling_factor: 2.5 # float, follow dsv3
